### ISSUE TITLE
Not working web applicaition

### ISSUE THREAD

**Issue by kdelinx** [MashaSamoylova/alice_akinator#1]
You havent not working web application, becase Flask with `werkzeug` not support async methods. This app must be just sync **OR** async type. Use Flask application handler or aiohttp server handler.

**Comment by mshsmlv** [comment]
@kdelinx смотри ветку dev 

в мастере паника и неработающий код, я в курсе

**Comment by kdelinx** [comment]
Всеравно совмещать Флакс в application.py и aiohttp.web в main - это анархия. Нинада так;)

**Comment by mshsmlv** [comment]
done
